### ISSUE TITLE
Avoid configuring the library using an extern variable

### ISSUE THREAD

**Issue by alranel** [arduino-libraries/Arduino_MKRIoTCarrier#13]
As of now, this library must be configured by declaring a global variable after including the library:

```c++
#include <Arduino_MKRIoTCarrier.h>
MKRIoTCarrier carrier;
bool CARRIER_CASE = false;
```

The variable is declared as `extern` in this library:

https://github.com/arduino-libraries/Arduino_MKRIoTCarrier/blob/788a4b026b55292fad8616b5354cc215b7be4d95/src/Arduino_MKRIoTCarrier.h#L80

If removed from the sketch, it will not compile.

This configuration pattern, however, might confuse users who (like me) see an unused variable and try to remove it. It's a bit obscure for basic users who don't know about `extern` symbols or the build process. Not really a big issue, but we should probably stick to a more explicit and Arduino-like pattern like:

```c+++
carrier.begin(CARRIER_CASE);
```
 
or even:

```c+++
carrier.withCase();
```

I wonder if there's a clever way to make this change in a retrocompatible fashion. :)

**Comment by aentinger** [comment]
I'd assign @marqdevx to this issue due to the fact he has effectively written the [whole library](https://github.com/arduino-libraries/Arduino_MKRIoTCarrier/graphs/contributors).

**Comment by marqdevx** [comment]
I will try to find another way to make it more simple with the team, thanks.

I will contact with you soon @alranel

**Comment by carterwe** [comment]
What difference does false or true make for CARRIER_CASE;

**Comment by marqdevx** [comment]
@carterwe 
true means that you have the Enclosure Case attached to the Carrier
false means that you DONT have the Enclosure Case attached to the Carrier

So it calibrates the touch buttons to be, in both cases, functional

**Comment by carterwe** [comment]
So it calibrates the touch buttons to be, in both cases, functional

Ah... this is what I was looking for!   I hear you guys will have complete
new project documentation  soon (even mentioning how to use and connect the
battery).  Very good!  I'm really looking forward to it.  I am application
programmer just  trying to pick up all this board connecting, Arduino C++,
and Arduino library stuff  up.  The better the documentation the way better
for me.  Thanks for your reply!   :) Ed

**Comment by marqdevx** [comment]
@carterwe Thanks!!

Please check the Reference page to read more :)
https://www.arduino.cc/reference/en/libraries/arduino_mkriotcarrier/

**Comment by alranel** [comment]
@marqdevx This issue is still valid :)
