### ISSUE TITLE
Button status gets stuck after being touched repeatedly

### ISSUE THREAD

**Issue by alranel** [arduino-libraries/Arduino_MKRIoTCarrier#14]
I'm testing 0.9.4 and I'm running into a problem with buttons. I wrote a very simple sketch to reproduce the issue:

```c++
#include <Arduino_MKRIoTCarrier.h>
bool CARRIER_CASE = true;
MKRIoTCarrier carrier;

void setup() {
  Serial.begin(9600);
  while (!Serial);  
  carrier.begin();
}

void loop() {
  carrier.Buttons.update();

  Serial.print("Sensors: ");
  Serial.print(TOUCH.read(0));
  Serial.print(" - ");
  Serial.println(TOUCH.read(1));
}
```

Now, if I try to touch the buttons their status is properly reflected in the console as 0/1 (unpressed/pressed). However, if I start tapping them quickly and repeatedly they get suddenly stuck in the pressed state (1) and they never go back to 0.

I haven't debugged the issue, but it may be a bug of the queue logic implemented in this library rather than an issue of the underlying Arduino_MCHPTouch library.

**Comment by marqdevx** [comment]
I tried yours, and yes im having the issue

Try this one, its working for me
```cpp
#include <Arduino_MKRIoTCarrier.h>
bool CARRIER_CASE = false;  
MKRIoTCarrier carrier;

void setup() {
  Serial.begin(9600);
  while (!Serial);  
  carrier.begin();
}

void loop() {
  carrier.Buttons.update();

  Serial.print("Sensors: ");
  Serial.print(carrier.Button1.getTouch());
  Serial.print(" - ");
  Serial.println(carrier.Button2.getTouch());
} 
```

**Comment by alranel** [comment]
It looks like setting `CARRIER_CASE = false` fixes the issue. Also putting the board in the case seems to be effective.
So the lesson learned is that it's important to set CARRIER_CASE appropriately because it doesn't only adjust sensitivity but ensures that the sensors work properly.

Thank you :)
