### ISSUE TITLE
Question: documentatio of Arduino_MKRIoTCarrier.h library

### ISSUE THREAD

**Issue by michaldengusiak** [arduino-libraries/Arduino_MKRIoTCarrier#27]
I am not able to find Arduino_MKRIoTCarrier when I scroll here
https://www.arduino.cc/reference/en/libraries/

I come across this one..is it the correct link? not sure why could not find from step above
https://www.arduino.cc/reference/en/libraries/arduino_mkriotcarrier/

but I am unable to find what functions we have for
`carrier.Env.`

we have a bit of inconsistency as we have

`carrier.Pressure.readPressure()`
but
`carrier.Env.readHumidity()`

this is due to different sensors?
1. do you have
`Env.readIlluminance() `? could not find it

2. how to turn off the screen to make sure will be off after a few sec from touch

I can see how to start 
`display.init`
but could not find out to turn off

**Comment by marqdevx** [comment]
Hey!
Thanks for the feedback, we will consider the renaming of that class for future updates.

At the first link they don't appear all the libraries from the library manager.

You have the commands for that sensor here https://www.arduino.cc/en/Reference/ArduinoHTS221
* `carrier.Env.readTemperature()`
* `carrier.Env.readHumidity()`

As far as I know the current library that we use for the display doesn't have any `end()` function, I will let you know if I find something, what you can do its declare again the class and maybe it resets.

**Comment by michaldengusiak** [comment]
yes turning off would be great, can wait for some workaround...

I found one missing line in your example, this is why it did not work for me...
I still have some issue with displaying Illuminance in Lux on board I got a feeling there is a mismatch with Units
https://create.arduino.cc/iot/dashboards/dbb9bfa2-1337-4dae-b8e0-df7e3a17d1e3
it works when I display it as a string but not when I display it as Value

![image](https://user-images.githubusercontent.com/26113670/115207693-ba6af180-a0f3-11eb-829c-57f5b49ddfd7.png)

**Comment by michaldengusiak** [comment]
wrong documentation - issue solved
https://forum.arduino.cc/t/iot-cloud-issue-with-variables-types-illuminance-always-zero/851879/3
light is Integer and need to be define again
