### ISSUE TITLE
Animated GIF examples broken

### ISSUE THREAD

**Issue by r-colvin** [arduino-libraries/Arduino_MKRIoTCarrier#30]
Opening bug report to link open issue in bitbank2 animated gif library : https://github.com/bitbank2/AnimatedGIF/issues/34?_pjax=%23js-repo-pjax-container which breaks the examples

**Comment by marqdevx** [comment]
Thanks!
In the CI validation, I set the version that was working, but I will have a look so when it gets fixed I will update it.
Have a nice one!

**Comment by marqdevx** [comment]
They released a version fixing the issue I will close this issue and add the new version to the CI compiling check.

https://github.com/bitbank2/AnimatedGIF/issues/34#issuecomment-855484533
