### ISSUE TITLE
error: 'AREF_PIN' was not declared in this scope

### ISSUE THREAD

**Issue by mgunjan** [arduino-libraries/Arduino_MKRIoTCarrier#74]
Installed the v2.0.4 from the library manager of the IDE and trying a test run using the "All_Features.ino" example. I am getting the error as shown below
```
Library Arduino_MKRIoTCarrier has been declared precompiled:
Using precompiled library in /Users/mgunjan/Documents/Arduino/libraries/Arduino_MKRIoTCarrier/src/cortex-m0plus
/Users/mgunjan/Documents/Arduino/libraries/Arduino_MKRIoTCarrier/src/Arduino_MKRIoTCarrier.cpp: In member function 'int MKRIoTCarrier::begin()':
/Users/mgunjan/Documents/Arduino/libraries/Arduino_MKRIoTCarrier/src/Arduino_MKRIoTCarrier.cpp:34:11: error: 'AREF_PIN' was not declared in this scope
   pinMode(AREF_PIN,INPUT_PULLUP);
           ^~~~~~~~
/Users/mgunjan/Documents/Arduino/libraries/Arduino_MKRIoTCarrier/src/Arduino_MKRIoTCarrier.cpp:34:11: note: suggested alternative: 'SCK_PIN'
   pinMode(AREF_PIN,INPUT_PULLUP);
           ^~~~~~~~
           SCK_PIN

exit status 1

Compilation error: exit status 1
```

**Comment by per1234** [comment]
Hi @mgunjan. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino-libraries/Arduino_MKRIoTCarrier/issues/68.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
